# Description

This notebook process the LINCS data consensus signatures from [here](https://figshare.com/articles/dataset/Consensus_signatures_for_LINCS_L1000_perturbations/3085426/1).

# Modules loading

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path

import pandas as pd

import rpy2.robjects as ro
from rpy2.robjects import pandas2ri
from rpy2.robjects.conversion import localconverter

import conf
from entity import Gene

In [3]:
readRDS = ro.r["readRDS"]

In [4]:
saveRDS = ro.r["saveRDS"]

# Settings

In [5]:
OUTPUT_DATA_DIR = Path(conf.RESULTS["DRUG_DISEASE_ANALYSES"], "lincs")
display(OUTPUT_DATA_DIR)
OUTPUT_DATA_DIR.mkdir(parents=True, exist_ok=True)

PosixPath('/home/miltondp/projects/labs/greenelab/phenoplier/base/results/drug_disease_analyses/lincs')

# Load LINCS consensus signatures

In [6]:
input_file = conf.LINCS["CONSENSUS_SIGNATURES_FILE"]

display(input_file)

PosixPath('/home/miltondp/projects/labs/greenelab/phenoplier/base/data/hetionet/lincs-v2.0/consensi-drugbank.tsv.bz2')

In [7]:
lincs_data = pd.read_csv(input_file, sep="\t", index_col="perturbagen").T

In [8]:
lincs_data.shape

(7467, 1170)

In [9]:
lincs_data.head()

perturbagen  DB00014  DB00091  DB00121  DB00130  DB00131  DB00132  DB00136  \
100           -1.001   -1.835    1.391    1.132    0.257    1.932    0.508   
1000           1.146   -1.863    0.011   -1.020    1.143   -0.115    1.327   
10000         -0.693    1.694   -0.804   -0.164    1.145   -1.465    1.221   
10001         -0.037    0.383    0.269   -0.997    0.185   -0.536    0.424   
10005          0.162   -0.899    0.105   -0.090   -1.291    1.404    0.185   

perturbagen  DB00140  DB00146  DB00150  ...  DB08995  DB09002  DB09004  \
100            1.408    0.777    0.032  ...   -1.692   -0.516   -1.435   
1000           0.310   -1.853    0.872  ...    0.354    0.498    0.268   
10000         -0.747    0.829   -0.961  ...   -1.196   -0.230   -1.049   
10001         -0.119   -1.313    0.579  ...   -0.343    0.116   -0.245   
10005          0.157   -0.327   -0.026  ...   -0.136   -1.115   -0.280   

perturbagen  DB09009  DB09010  DB09015  DB09019  DB09020  DB09022  DB09023  
100           -0.317   -0.012    0.641   -0.230   -0.518   -0.177    2.146  
1000          -1.084   -0.142   -0.077    0.633   -1.807    0.032    0.135  
10000         -0.347    0.586    0.865   -0.021    2.180   -0.956    0.105  
10001         -0.127   -1.367    0.149    0.117    2.084    1.178    0.772  
10005          0.200    0.638   -0.197   -0.360   -2.302   -0.117   -0.167  

[5 rows x 1170 columns]

In [10]:
assert lincs_data.index.is_unique

In [11]:
# check that DrugBank ids are consistent
_tmp = lincs_data.columns.map(len).unique()
assert _tmp.shape[0] == 1

In [12]:
assert lincs_data.columns.is_unique

## Gene IDs to Gene names

In [13]:
from rpy2.robjects.packages import importr
import rpy2.robjects as robjects
from rpy2.robjects import pandas2ri

pandas2ri.activate()

In [14]:
clusterProfiler = importr("clusterProfiler")

In [15]:
_now_mapped_genes = clusterProfiler.bitr(
    lincs_data.index.tolist(),
    fromType="ENTREZID",
    toType="ENSEMBL",
    OrgDb="org.Hs.eg.db",
)

R[write to console]: Loading required package: org.Hs.eg.db

R[write to console]: Loading required package: AnnotationDbi

R[write to console]: Loading required package: stats4

R[write to console]: Loading required package: BiocGenerics

R[write to console]: Loading required package: parallel

R[write to console]: 
Attaching package: ‘BiocGenerics’


R[write to console]: The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB


R[write to console]: The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


R[write to console]: The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, m

In [16]:
_now_mapped_genes.shape

(8259, 2)

In [17]:
# some genes have entrez ids that map to several ensembl id
display(_now_mapped_genes[_now_mapped_genes["ENTREZID"].duplicated(keep=False)])

ENTREZID          ENSEMBL
3         10000  ENSG00000117020
4         10000  ENSG00000275199
12    100129361  ENSG00000256537
13    100129361  ENSG00000262986
14    100129361  ENSG00000281930
...         ...              ...
8202       9859  ENSG00000276725
8243       9920  ENSG00000176595
8244       9920  ENSG00000273645
8288       9994  ENSG00000118412
8289       9994  ENSG00000288475

[1232 rows x 2 columns]

In [18]:
_now_mapped_genes = _now_mapped_genes.assign(
    in_phenomexcan=_now_mapped_genes["ENSEMBL"].apply(
        lambda x: x in Gene.GENE_ID_TO_NAME_MAP
    )
)

In [19]:
_now_mapped_genes[_now_mapped_genes["in_phenomexcan"]].shape

(7125, 3)

In [20]:
_now_mapped_genes.head()

ENTREZID          ENSEMBL  in_phenomexcan
1      100  ENSG00000196839            True
2     1000  ENSG00000170558            True
3    10000  ENSG00000117020            True
4    10000  ENSG00000275199           False
5    10001  ENSG00000133997            True

In [21]:
_now_mapped_genes = _now_mapped_genes[
    _now_mapped_genes["in_phenomexcan"]
].drop_duplicates(subset=["ENTREZID"])

In [22]:
_now_mapped_genes.shape

(7120, 3)

In [23]:
_now_mapped_genes.head()

ENTREZID          ENSEMBL  in_phenomexcan
1      100  ENSG00000196839            True
2     1000  ENSG00000170558            True
3    10000  ENSG00000117020            True
5    10001  ENSG00000133997            True
6    10005  ENSG00000101473            True

In [24]:
_now_mapped_genes_dict = _now_mapped_genes.set_index("ENTREZID").to_dict()["ENSEMBL"]

In [25]:
lincs_data = lincs_data.loc[_now_mapped_genes_dict.keys()].rename(
    index=_now_mapped_genes_dict
)

In [26]:
lincs_data.head()

perturbagen      DB00014  DB00091  DB00121  DB00130  DB00131  DB00132  \
ENSG00000196839   -1.001   -1.835    1.391    1.132    0.257    1.932   
ENSG00000170558    1.146   -1.863    0.011   -1.020    1.143   -0.115   
ENSG00000117020   -0.693    1.694   -0.804   -0.164    1.145   -1.465   
ENSG00000133997   -0.037    0.383    0.269   -0.997    0.185   -0.536   
ENSG00000101473    0.162   -0.899    0.105   -0.090   -1.291    1.404   

perturbagen      DB00136  DB00140  DB00146  DB00150  ...  DB08995  DB09002  \
ENSG00000196839    0.508    1.408    0.777    0.032  ...   -1.692   -0.516   
ENSG00000170558    1.327    0.310   -1.853    0.872  ...    0.354    0.498   
ENSG00000117020    1.221   -0.747    0.829   -0.961  ...   -1.196   -0.230   
ENSG00000133997    0.424   -0.119   -1.313    0.579  ...   -0.343    0.116   
ENSG00000101473    0.185    0.157   -0.327   -0.026  ...   -0.136   -1.115   

perturbagen      DB09004  DB09009  DB09010  DB09015  DB09019  DB09020  \
ENSG00000196839   -1.435   -0.317   -0.012    0.641   -0.230   -0.518   
ENSG00000170558    0.268   -1.084   -0.142   -0.077    0.633   -1.807   
ENSG00000117020   -1.049   -0.347    0.586    0.865   -0.021    2.180   
ENSG00000133997   -0.245   -0.127   -1.367    0.149    0.117    2.084   
ENSG00000101473   -0.280    0.200    0.638   -0.197   -0.360   -2.302   

perturbagen      DB09022  DB09023  
ENSG00000196839   -0.177    2.146  
ENSG00000170558    0.032    0.135  
ENSG00000117020   -0.956    0.105  
ENSG00000133997    1.178    0.772  
ENSG00000101473   -0.117   -0.167  

[5 rows x 1170 columns]

In [27]:
# make sure we have ensembl id only in the index
_tmp = pd.Series(lincs_data.index.map(len)).value_counts()
display(_tmp)
assert _tmp.shape[0] == 1

15    7120
dtype: int64

In [28]:
lincs_data.head()

perturbagen      DB00014  DB00091  DB00121  DB00130  DB00131  DB00132  \
ENSG00000196839   -1.001   -1.835    1.391    1.132    0.257    1.932   
ENSG00000170558    1.146   -1.863    0.011   -1.020    1.143   -0.115   
ENSG00000117020   -0.693    1.694   -0.804   -0.164    1.145   -1.465   
ENSG00000133997   -0.037    0.383    0.269   -0.997    0.185   -0.536   
ENSG00000101473    0.162   -0.899    0.105   -0.090   -1.291    1.404   

perturbagen      DB00136  DB00140  DB00146  DB00150  ...  DB08995  DB09002  \
ENSG00000196839    0.508    1.408    0.777    0.032  ...   -1.692   -0.516   
ENSG00000170558    1.327    0.310   -1.853    0.872  ...    0.354    0.498   
ENSG00000117020    1.221   -0.747    0.829   -0.961  ...   -1.196   -0.230   
ENSG00000133997    0.424   -0.119   -1.313    0.579  ...   -0.343    0.116   
ENSG00000101473    0.185    0.157   -0.327   -0.026  ...   -0.136   -1.115   

perturbagen      DB09004  DB09009  DB09010  DB09015  DB09019  DB09020  \
ENSG00000196839   -1.435   -0.317   -0.012    0.641   -0.230   -0.518   
ENSG00000170558    0.268   -1.084   -0.142   -0.077    0.633   -1.807   
ENSG00000117020   -1.049   -0.347    0.586    0.865   -0.021    2.180   
ENSG00000133997   -0.245   -0.127   -1.367    0.149    0.117    2.084   
ENSG00000101473   -0.280    0.200    0.638   -0.197   -0.360   -2.302   

perturbagen      DB09022  DB09023  
ENSG00000196839   -0.177    2.146  
ENSG00000170558    0.032    0.135  
ENSG00000117020   -0.956    0.105  
ENSG00000133997    1.178    0.772  
ENSG00000101473   -0.117   -0.167  

[5 rows x 1170 columns]

## Remove NaN values

In [29]:
assert not lincs_data.isna().any().any()

## Save

In [30]:
output_file = Path(OUTPUT_DATA_DIR, "lincs-data.pkl").resolve()
display(output_file)

PosixPath('/home/miltondp/projects/labs/greenelab/phenoplier/base/results/drug_disease_analyses/lincs/lincs-data.pkl')

In [31]:
lincs_data.to_pickle(output_file)

### RDS format

In [32]:
output_rds_file = output_file.with_suffix(".rds")
display(output_rds_file)

PosixPath('/home/miltondp/projects/labs/greenelab/phenoplier/base/results/drug_disease_analyses/lincs/lincs-data.rds')

In [33]:
with localconverter(ro.default_converter + pandas2ri.converter):
    data_r = ro.conversion.py2rpy(lincs_data)

In [34]:
data_r

R object with classes: ('data.frame',) mapped to:
[FloatSexp..., FloatSexp..., FloatSexp..., FloatSexp..., ..., FloatSexp..., FloatSexp..., FloatSexp..., FloatSexp...]
  DB00014: <class 'numpy.ndarray'>
  array([-1.001,  1.146, -0.693, ..., -0.734, -0.048,  0.036])
  DB00091: <class 'numpy.ndarray'>
  array([-1.835, -1.863,  1.694, ...,  4.382,  0.266, -4.995])
  DB00121: <class 'numpy.ndarray'>
  array([ 1.391,  0.011, -0.804, ..., -1.897, -0.299, -0.732])
  DB00130: <class 'numpy.ndarray'>
  array([ 1.132, -1.02 , -0.164, ...,  0.134,  0.147,  2.158])
...
  DB00132: <class 'numpy.ndarray'>
  array([-0.23 ,  0.633, -0.021, ...,  2.358, -0.768, -0.319])
  DB00136: <class 'numpy.ndarray'>
  array([-0.518, -1.807,  2.18 , ...,  2.4  ,  1.412, -0.522])
  DB00140: <class 'numpy.ndarray'>
  array([-0.177,  0.032, -0.956, ..., -1.163,  1.264,  0.379])
  DB00146: <class 'numpy.ndarray'>
  array([ 2.146,  0.135,  0.105, ..., -0.921,  1.121, -0.739])

In [35]:
saveRDS(data_r, str(output_rds_file))

<rpy2.rinterface_lib.sexp.NULLType object at 0x7f386244ca80> [RTYPES.NILSXP]

In [36]:
# testing: load the rds file again
data_r = readRDS(str(output_rds_file))

In [37]:
with localconverter(ro.default_converter + pandas2ri.converter):
    data_again = ro.conversion.rpy2py(data_r)
#     data_again.index = data_again.index.astype(int)

In [38]:
data_again.shape

(7120, 1170)

In [39]:
data_again.head()

DB00014  DB00091  DB00121  DB00130  DB00131  DB00132  \
ENSG00000196839   -1.001   -1.835    1.391    1.132    0.257    1.932   
ENSG00000170558    1.146   -1.863    0.011   -1.020    1.143   -0.115   
ENSG00000117020   -0.693    1.694   -0.804   -0.164    1.145   -1.465   
ENSG00000133997   -0.037    0.383    0.269   -0.997    0.185   -0.536   
ENSG00000101473    0.162   -0.899    0.105   -0.090   -1.291    1.404   

                 DB00136  DB00140  DB00146  DB00150  ...  DB08995  DB09002  \
ENSG00000196839    0.508    1.408    0.777    0.032  ...   -1.692   -0.516   
ENSG00000170558    1.327    0.310   -1.853    0.872  ...    0.354    0.498   
ENSG00000117020    1.221   -0.747    0.829   -0.961  ...   -1.196   -0.230   
ENSG00000133997    0.424   -0.119   -1.313    0.579  ...   -0.343    0.116   
ENSG00000101473    0.185    0.157   -0.327   -0.026  ...   -0.136   -1.115   

                 DB09004  DB09009  DB09010  DB09015  DB09019  DB09020  \
ENSG00000196839   -1.435   -0.317   -0.012    0.641   -0.230   -0.518   
ENSG00000170558    0.268   -1.084   -0.142   -0.077    0.633   -1.807   
ENSG00000117020   -1.049   -0.347    0.586    0.865   -0.021    2.180   
ENSG00000133997   -0.245   -0.127   -1.367    0.149    0.117    2.084   
ENSG00000101473   -0.280    0.200    0.638   -0.197   -0.360   -2.302   

                 DB09022  DB09023  
ENSG00000196839   -0.177    2.146  
ENSG00000170558    0.032    0.135  
ENSG00000117020   -0.956    0.105  
ENSG00000133997    1.178    0.772  
ENSG00000101473   -0.117   -0.167  

[5 rows x 1170 columns]

In [40]:
pd.testing.assert_frame_equal(
    lincs_data,
    data_again,
    check_names=False,
    check_exact=True,
    #     rtol=0.0,
    #     atol=1e-50,
    #     check_dtype=False,
)

### Text format

In [41]:
# tsv format
output_text_file = output_file.with_suffix(".tsv.gz")
display(output_text_file)

PosixPath('/home/miltondp/projects/labs/greenelab/phenoplier/base/results/drug_disease_analyses/lincs/lincs-data.tsv.gz')

In [42]:
lincs_data.to_csv(output_text_file, sep="\t", index=True, float_format="%.5e")

In [43]:
# testing
# data2 = data.copy()
# data2.index = list(range(0, data2.shape[0]))

data_again = pd.read_csv(output_text_file, sep="\t", index_col=0)

# data_again.index = list(data_again.index)
# data_again["part_k"] = data_again["part_k"].astype(float)

In [44]:
data_again.shape

(7120, 1170)

In [45]:
data_again.head()

DB00014  DB00091  DB00121  DB00130  DB00131  DB00132  \
ENSG00000196839   -1.001   -1.835    1.391    1.132    0.257    1.932   
ENSG00000170558    1.146   -1.863    0.011   -1.020    1.143   -0.115   
ENSG00000117020   -0.693    1.694   -0.804   -0.164    1.145   -1.465   
ENSG00000133997   -0.037    0.383    0.269   -0.997    0.185   -0.536   
ENSG00000101473    0.162   -0.899    0.105   -0.090   -1.291    1.404   

                 DB00136  DB00140  DB00146  DB00150  ...  DB08995  DB09002  \
ENSG00000196839    0.508    1.408    0.777    0.032  ...   -1.692   -0.516   
ENSG00000170558    1.327    0.310   -1.853    0.872  ...    0.354    0.498   
ENSG00000117020    1.221   -0.747    0.829   -0.961  ...   -1.196   -0.230   
ENSG00000133997    0.424   -0.119   -1.313    0.579  ...   -0.343    0.116   
ENSG00000101473    0.185    0.157   -0.327   -0.026  ...   -0.136   -1.115   

                 DB09004  DB09009  DB09010  DB09015  DB09019  DB09020  \
ENSG00000196839   -1.435   -0.317   -0.012    0.641   -0.230   -0.518   
ENSG00000170558    0.268   -1.084   -0.142   -0.077    0.633   -1.807   
ENSG00000117020   -1.049   -0.347    0.586    0.865   -0.021    2.180   
ENSG00000133997   -0.245   -0.127   -1.367    0.149    0.117    2.084   
ENSG00000101473   -0.280    0.200    0.638   -0.197   -0.360   -2.302   

                 DB09022  DB09023  
ENSG00000196839   -0.177    2.146  
ENSG00000170558    0.032    0.135  
ENSG00000117020   -0.956    0.105  
ENSG00000133997    1.178    0.772  
ENSG00000101473   -0.117   -0.167  

[5 rows x 1170 columns]

In [46]:
pd.testing.assert_frame_equal(
    lincs_data,
    data_again,
    check_names=False,
    check_exact=False,
    rtol=0.0,
    atol=5e-5,
)

# Project into MultiPLIER

In [47]:
from multiplier import MultiplierProjection

In [48]:
mproj = MultiplierProjection()

In [49]:
lincs_projection = mproj.transform(lincs_data)

In [50]:
lincs_projection.shape

(987, 1170)

In [51]:
lincs_projection.head()

perturbagen   DB00014   DB00091   DB00121   DB00130   DB00131   DB00132  \
LV1          0.036115 -0.358610  0.091067  0.008923  0.046469  0.136747   
LV2          0.012281  0.009738  0.004650 -0.006554  0.021758  0.010425   
LV3         -0.005533 -0.059174  0.013454  0.008906 -0.004939  0.033663   
LV4         -0.004151 -0.032884  0.005934 -0.003991 -0.028524  0.002709   
LV5         -0.015156 -0.005276  0.025747  0.000346 -0.013932 -0.010911   

perturbagen   DB00136   DB00140   DB00146   DB00150  ...   DB08995   DB09002  \
LV1          0.036151  0.034024 -0.027445  0.060644  ...  0.069930  0.021537   
LV2          0.000794 -0.000603  0.011534 -0.004425  ...  0.000344  0.001123   
LV3         -0.010045  0.003824  0.009814 -0.007492  ... -0.021941 -0.002417   
LV4          0.007001  0.024704  0.005058 -0.004345  ...  0.013806  0.003197   
LV5          0.041403 -0.018285  0.003507 -0.007621  ... -0.011577 -0.015956   

perturbagen   DB09004   DB09009   DB09010   DB09015   DB09019   DB09020  \
LV1          0.020511 -0.006250 -0.002660 -0.017210 -0.004029 -0.145490   
LV2         -0.012675 -0.004849  0.000375  0.002623 -0.003252 -0.066209   
LV3          0.000155  0.002941 -0.015100 -0.016372  0.012249  0.009216   
LV4          0.013099  0.002643 -0.008836  0.023852  0.028957  0.014681   
LV5         -0.027614 -0.001707 -0.000542 -0.016918  0.001959  0.024147   

perturbagen   DB09022   DB09023  
LV1          0.102504  0.057621  
LV2          0.025378  0.012453  
LV3          0.018254 -0.003516  
LV4          0.000826 -0.009739  
LV5          0.013004 -0.014166  

[5 rows x 1170 columns]

In [52]:
assert not lincs_projection.isna().any().any()

## Save

In [53]:
output_file = Path(OUTPUT_DATA_DIR, "lincs-projection.pkl").resolve()
display(output_file)

PosixPath('/home/miltondp/projects/labs/greenelab/phenoplier/base/results/drug_disease_analyses/lincs/lincs-projection.pkl')

In [54]:
lincs_projection.to_pickle(output_file)

### RDS format

In [55]:
output_rds_file = output_file.with_suffix(".rds")
display(output_rds_file)

PosixPath('/home/miltondp/projects/labs/greenelab/phenoplier/base/results/drug_disease_analyses/lincs/lincs-projection.rds')

In [56]:
with localconverter(ro.default_converter + pandas2ri.converter):
    data_r = ro.conversion.py2rpy(lincs_projection)

In [57]:
data_r

R object with classes: ('data.frame',) mapped to:
[FloatSexp..., FloatSexp..., FloatSexp..., FloatSexp..., ..., FloatSexp..., FloatSexp..., FloatSexp..., FloatSexp...]
  DB00014: <class 'numpy.ndarray'>
  array([ 3.61149415e-02,  1.22809629e-02, -5.53343226e-03, -4.15102355e-03,
       -1.51559562e-02, -1.08612265e-02,  8.18105567e-03, -8.14810614e-03,
        4.94755326e-03, -9.86929880e-03,  4.20045218e-03, -1.11463968e-02,
        6.36400227e-03,  7.31004570e-03, -2.71300169e-02,  2.12043040e-02,
       -3.69639618e-04,  1.00098610e-02, -1.42683524e-02,  5.23920807e-03,
        1.10821720e-02, -8.03455482e-03, -6.17510694e-03,  7.56130830e-03,
       -8.36001895e-04, -4.68253713e-03, -4.53671958e-02, -1.94690020e-02,
        3.25767636e-04, -1.00172698e-02, -2.56245392e-02,  4.38135698e-03,
        1.09192594e-02, -1.40245316e-02, -4.41084039e-03,  3.46777884e-03,
        7.07337964e-03,  4.69701811e-02, -2.88538304e-03, -2.99048176e-03,
        3.77936464e-03,  9.42770938e-03, -2.59575749e-03, -1.93940454e-02,
       -6.66074269e-03, -8.04311249e-03, -4.45399553e-03,  1.46720663e-02,
       -4.27144550e-03, -2.07002891e-02, -1.94108890e-03, -1.03559359e-02,
       -1.06643238e-02, -5.82244218e-04,  1.90861277e-03,  9.79380421e-03,
        4.32389137e-03,  3.80799743e-03,  1.09154263e-02, -2.17530121e-03,
       -9.15189186e-03, -1.03594938e-02, -3.66643184e-03,  1.44303491e-02,
        1.92043221e-02, -2.20425556e-04, -1.28034748e-02,  6.40790261e-03,
        2.77757661e-03,  1.81797551e-02, -8.09400306e-04,  8.09214045e-03,
        8.12242856e-03, -3.58851896e-02, -1.86347601e-03, -2.28229400e-03,
       -1.88198544e-03,  2.01599971e-04,  2.18323285e-03, -2.72880512e-03,
       -2.45231489e-02, -1.41065479e-02,  7.44079894e-03,  5.55571130e-03,
        1.22451979e-03, -7.68601140e-04,  4.06972283e-04, -2.63556715e-03,
        3.89541536e-03,  7.89434807e-03, -3.41298315e-03,  1.06952470e-02,
       -5.27704005e-03,  3.25740300e-04, -2.62969055e-02, -1.52494705e-02,
        9.72843369e-03,  1.45097675e-02,  1.91585686e-02, -1.98459986e-03,
        1.42301552e-02, -4.20327645e-03, -1.08262397e-02,  2.41585949e-02,
        1.70974208e-04,  4.75426010e-03,  1.63759746e-02, -1.33343055e-03,
       -1.43767324e-02, -3.02292917e-03, -4.36351408e-03, -6.62278779e-03,
       -2.53843238e-03, -4.54289924e-03, -2.21441639e-03,  5.98040742e-03,
       -7.88580266e-03, -2.13008376e-02, -8.69019561e-04,  8.81828535e-03,
        2.18490303e-02, -1.14251178e-03, -7.22397586e-03,  9.81932002e-03,
        1.84485799e-03,  3.17016420e-03,  1.51523082e-03,  6.71689341e-03,
        4.13965306e-03,  4.96385292e-03,  3.52943733e-03, -4.74331798e-03,
        1.73459428e-03, -6.41855929e-03, -7.87739673e-03,  1.16729785e-03,
        1.10993303e-02,  7.30021156e-03, -1.49231499e-02, -1.06458171e-02,
        1.75480780e-02, -6.47282165e-03, -1.03532920e-02,  1.82629508e-02,
        1.62659389e-03, -2.16472215e-03,  1.05713513e-02,  9.62873247e-03,
        7.88313069e-04,  1.35417495e-03, -5.03053337e-03,  1.47106074e-02,
       -1.97093827e-02,  4.26051258e-03, -1.66723265e-02, -2.74879588e-03,
       -8.25667997e-03,  1.92797959e-03, -2.40523878e-03, -6.76860715e-03,
       -5.22627519e-02, -8.83738637e-03, -1.63874712e-03,  1.14464339e-02,
        4.07513686e-03,  1.19428498e-02,  1.03580463e-02,  3.74183997e-03,
        2.40394495e-03,  7.13624385e-03, -9.72578115e-03, -7.34792943e-03,
        5.14467795e-03, -6.73914553e-06,  1.32791210e-02,  5.50579311e-04,
       -4.49016683e-04,  9.76068171e-03,  5.39741476e-03,  4.86354577e-03,
       -4.87948230e-04,  1.72531501e-02,  1.23368216e-03, -5.44018729e-03,
       -6.58097843e-03, -5.74597844e-03, -1.75760075e-02, -1.03522915e-02,
        1.21584143e-02,  4.41972541e-03, -3.66178745e-04, -2.23181330e-03,
        1.68000897e-02,  7.69169430e-03, -3.24239591e-03, -6.23714766e-03,
       -4.00280794e-03, -1.15337945e-02, -1.81814815e-03,  9.19139034e-04,
       -1.03311312e-02,  1.56651892e-02, -1.1

In [58]:
saveRDS(data_r, str(output_rds_file))

<rpy2.rinterface_lib.sexp.NULLType object at 0x7f386244ca80> [RTYPES.NILSXP]

In [59]:
# testing: load the rds file again
data_r = readRDS(str(output_rds_file))

In [60]:
with localconverter(ro.default_converter + pandas2ri.converter):
    data_again = ro.conversion.rpy2py(data_r)
#     data_again.index = data_again.index.astype(int)

In [61]:
data_again.shape

(987, 1170)

In [62]:
data_again.head()

DB00014   DB00091   DB00121   DB00130   DB00131   DB00132   DB00136  \
LV1  0.036115 -0.358610  0.091067  0.008923  0.046469  0.136747  0.036151   
LV2  0.012281  0.009738  0.004650 -0.006554  0.021758  0.010425  0.000794   
LV3 -0.005533 -0.059174  0.013454  0.008906 -0.004939  0.033663 -0.010045   
LV4 -0.004151 -0.032884  0.005934 -0.003991 -0.028524  0.002709  0.007001   
LV5 -0.015156 -0.005276  0.025747  0.000346 -0.013932 -0.010911  0.041403   

      DB00140   DB00146   DB00150  ...   DB08995   DB09002   DB09004  \
LV1  0.034024 -0.027445  0.060644  ...  0.069930  0.021537  0.020511   
LV2 -0.000603  0.011534 -0.004425  ...  0.000344  0.001123 -0.012675   
LV3  0.003824  0.009814 -0.007492  ... -0.021941 -0.002417  0.000155   
LV4  0.024704  0.005058 -0.004345  ...  0.013806  0.003197  0.013099   
LV5 -0.018285  0.003507 -0.007621  ... -0.011577 -0.015956 -0.027614   

      DB09009   DB09010   DB09015   DB09019   DB09020   DB09022   DB09023  
LV1 -0.006250 -0.002660 -0.017210 -0.004029 -0.145490  0.102504  0.057621  
LV2 -0.004849  0.000375  0.002623 -0.003252 -0.066209  0.025378  0.012453  
LV3  0.002941 -0.015100 -0.016372  0.012249  0.009216  0.018254 -0.003516  
LV4  0.002643 -0.008836  0.023852  0.028957  0.014681  0.000826 -0.009739  
LV5 -0.001707 -0.000542 -0.016918  0.001959  0.024147  0.013004 -0.014166  

[5 rows x 1170 columns]

In [63]:
pd.testing.assert_frame_equal(
    lincs_projection,
    data_again,
    check_names=False,
    check_exact=True,
    #     rtol=0.0,
    #     atol=1e-50,
    #     check_dtype=False,
)

### Text format

In [64]:
# tsv format
output_text_file = output_file.with_suffix(".tsv.gz")
display(output_text_file)

PosixPath('/home/miltondp/projects/labs/greenelab/phenoplier/base/results/drug_disease_analyses/lincs/lincs-projection.tsv.gz')

In [65]:
lincs_projection.to_csv(output_text_file, sep="\t", index=True, float_format="%.5e")

In [66]:
# testing
# data2 = data.copy()
# data2.index = list(range(0, data2.shape[0]))

data_again = pd.read_csv(output_text_file, sep="\t", index_col=0)

# data_again.index = list(data_again.index)
# data_again["part_k"] = data_again["part_k"].astype(float)

In [67]:
data_again.shape

(987, 1170)

In [68]:
data_again.head()

DB00014   DB00091   DB00121   DB00130   DB00131   DB00132   DB00136  \
LV1  0.036115 -0.358610  0.091067  0.008923  0.046469  0.136747  0.036151   
LV2  0.012281  0.009738  0.004650 -0.006554  0.021758  0.010425  0.000794   
LV3 -0.005533 -0.059174  0.013454  0.008906 -0.004939  0.033663 -0.010045   
LV4 -0.004151 -0.032884  0.005934 -0.003991 -0.028524  0.002709  0.007001   
LV5 -0.015156 -0.005276  0.025747  0.000346 -0.013932 -0.010911  0.041403   

      DB00140   DB00146   DB00150  ...   DB08995   DB09002   DB09004  \
LV1  0.034024 -0.027445  0.060644  ...  0.069930  0.021537  0.020511   
LV2 -0.000603  0.011534 -0.004425  ...  0.000344  0.001123 -0.012675   
LV3  0.003824  0.009814 -0.007492  ... -0.021941 -0.002417  0.000155   
LV4  0.024704  0.005058 -0.004345  ...  0.013806  0.003197  0.013099   
LV5 -0.018285  0.003507 -0.007621  ... -0.011577 -0.015956 -0.027614   

      DB09009   DB09010   DB09015   DB09019   DB09020   DB09022   DB09023  
LV1 -0.006250 -0.002660 -0.017210 -0.004029 -0.145490  0.102504  0.057621  
LV2 -0.004849  0.000375  0.002623 -0.003252 -0.066209  0.025378  0.012453  
LV3  0.002941 -0.015100 -0.016372  0.012249  0.009216  0.018254 -0.003516  
LV4  0.002643 -0.008836  0.023852  0.028957  0.014681  0.000826 -0.009739  
LV5 -0.001707 -0.000542 -0.016918  0.001959  0.024147  0.013004 -0.014166  

[5 rows x 1170 columns]

In [69]:
pd.testing.assert_frame_equal(
    lincs_projection,
    data_again,
    check_names=False,
    check_exact=False,
    rtol=0.0,
    atol=5e-5,
)